services:
  app:
    build: .
    container_name: app_container
    restart: always
    command: python manage.py runserver 8006
    volumes:
      - data:/code/
    expose:
      - "8006"
    ports:
      - "8006:8006"

volumes:
  data: