services:
  app:
    build: .
    container_name: app_container
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - data:/code/
    expose:
      - 8000

volumes:
  data: